name: dog_gromming_website
description: Dog grooming website for Mimos

publish_to: 'none'

version: 1.3.0+3

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  dio: ^5.9.0
  easy_localization: ^3.0.8
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.3
  flutter_widget_from_html: ^0.17.1
  get_it: ^9.2.0
  go_router: ^17.0.0
  injectable: ^2.7.1
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/licenses/
    - assets/html/
    - assets/icons/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-SemiBold.ttf
          weight: 600
